apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
    name: www
  selector:
    app: {{ .Values.app }}