apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.service.metadata.namespace }}
spec:
  type: {{ .Values.service.spec.type }} 
  ports:
    - protocol: {{ .Values.service.spec.ports.protocol }}
      port: {{ .Values.service.spec.ports.port }}
      targetPort: {{ .Values.service.spec.ports.targetPort }}
      name: {{ .Values.service.metadata.name }}