# Default values for cassandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  metadata:
    name: sql-dev-lb
    namespace: dev     
  spec:
    type: ClusterIP
    ports:
      protocol: TCP
      port: 3306
      targetPort: 3306

endpoints:
  metadata:
    name: sql-dev-lb
    namespace: apple
  addresses:
    ip: 10.15.0.41
  ports:
    port: 3306

